import React, { createContext, useEffect, useMemo, useState } from 'react';

const translations = {
  en: {
    dashboard: 'Dashboard',
    products: 'Products',
    inventory: 'Inventory',
    purchasing: 'Purchasing',
    suppliers: 'Suppliers',
    customers: 'Customers',
    humanResources: 'Human Resources',
    production: 'Production',
    salesPos: 'Sales / POS',
    reporting: 'Reporting',
    users: 'User Administration',
    settings: 'Settings',
    inventorySystem: 'Inventory System',
    logout: 'Logout',
    welcomeBack: 'Welcome back',
    signInSubtitle: 'Sign in to manage daily operations.',
    emailAddress: 'Email address',
    password: 'Password',
    signInSecurely: 'Sign in securely',
    authenticating: 'Authenticating...',
    salesSubtitle: 'Register sales, validate stock, and deduct inventory automatically.',
    productsCount: 'saleable',
    currentSale: 'Current Sale',
    customer: 'Customer',
    customerEmail: 'Customer Email',
    retailCustomer: 'Retail Customer',
    receiptDraft: 'Optional receipt draft',
    searchProducts: 'Search product, SKU, or category',
    selectProducts: 'Select products to begin a sale.',
    units: 'Units',
    revenue: 'Revenue',
    grossProfit: 'Gross Profit',
    margin: 'Margin',
    paymentMethod: 'Payment Method',
    amountPaid: 'Amount Paid',
    change: 'Change',
    remaining: 'Remaining',
    completeSale: 'Complete Sale',
    processingSale: 'Processing sale...',
    recentSales: 'Recent Sales',
    records: 'records',
    seller: 'Seller',
    receipt: 'Receipt',
    open: 'Open',
    print: 'Print',
    pdf: 'PDF',
    emailDraft: 'Email Draft',
    stockInventory: 'Stock & Inventory',
    receiveStock: 'Receive Stock',
    adjustStock: 'Adjust Stock',
    receive: 'Receive',
    product: 'Product',
    category: 'Category',
    unitCost: 'Unit Cost',
    qtyOnHand: 'Qty on Hand',
    totalValue: 'Total Value',
    action: 'Action',
    noProducts: 'No products found matching the current filter.',
  },
  pt: {
    dashboard: 'Painel',
    products: 'Produtos',
    inventory: 'Inventário',
    purchasing: 'Compras',
    suppliers: 'Fornecedores',
    customers: 'Clientes',
    humanResources: 'Recursos Humanos',
    production: 'Produção',
    salesPos: 'Vendas / Caixa',
    reporting: 'Relatórios',
    users: 'Administração de Utilizadores',
    settings: 'Definições',
    inventorySystem: 'Sistema de Inventário',
    logout: 'Sair',
    welcomeBack: 'Bem-vindo de volta',
    signInSubtitle: 'Entre para gerir as operações diárias.',
    emailAddress: 'Email',
    password: 'Senha',
    signInSecurely: 'Entrar com segurança',
    authenticating: 'A autenticar...',
    salesSubtitle: 'Registe vendas, valide stock e desconte inventário automaticamente.',
    productsCount: 'à venda',
    currentSale: 'Venda Atual',
    customer: 'Cliente',
    customerEmail: 'Email do Cliente',
    retailCustomer: 'Cliente de Balcão',
    receiptDraft: 'Opcional para rascunho de recibo',
    searchProducts: 'Pesquisar produto, SKU ou categoria',
    selectProducts: 'Selecione produtos para iniciar a venda.',
    units: 'Unidades',
    revenue: 'Receita',
    grossProfit: 'Lucro Bruto',
    margin: 'Margem',
    paymentMethod: 'Método de Pagamento',
    amountPaid: 'Valor Pago',
    change: 'Troco',
    remaining: 'Em Falta',
    completeSale: 'Finalizar Venda',
    processingSale: 'A processar venda...',
    recentSales: 'Vendas Recentes',
    records: 'registos',
    seller: 'Vendedor',
    receipt: 'Recibo',
    open: 'Abrir',
    print: 'Imprimir',
    pdf: 'PDF',
    emailDraft: 'Rascunho Email',
    stockInventory: 'Stock & Inventário',
    receiveStock: 'Receber Stock',
    adjustStock: 'Ajustar Stock',
    receive: 'Receber',
    product: 'Produto',
    category: 'Categoria',
    unitCost: 'Custo Unitário',
    qtyOnHand: 'Qtd. em Stock',
    totalValue: 'Valor Total',
    action: 'Ação',
    noProducts: 'Nenhum produto encontrado para este filtro.',
  },
};

export const LanguageContext = createContext();

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState(() => localStorage.getItem('soul_language') || 'en');

  useEffect(() => {
    localStorage.setItem('soul_language', language);
  }, [language]);

  const value = useMemo(() => ({
    language,
    setLanguage,
    t: translations[language],
  }), [language]);

  return (
    <LanguageContext.Provider value={value}>
      {children}
    </LanguageContext.Provider>
  );
};
