import React, { createContext, useEffect, useMemo, useState } from 'react';

const translations = {
  en: {
    dashboard: 'Dashboard',
    products: 'Products',
    inventory: 'Inventory',
    purchasing: 'Purchasing',
    suppliers: 'Suppliers',
    customers: 'Loyalty',
    sellersResellers: 'Sellers & Resellers',
    humanResources: 'Human Resources',
    production: 'Production',
    salesPos: 'Sales / POS',
    reporting: 'Reporting',
    auditLogs: 'Audit Logs',
    users: 'User Administration',
    settings: 'Settings',
    inventorySystem: 'Inventory System',
    logout: 'Logout',
    welcomeBack: 'Welcome back',
    signInSubtitle: 'Sign in to manage daily operations.',
    emailAddress: 'Email address',
    loginIdentifier: 'Email, username or phone',
    password: 'Password',
    signInSecurely: 'Sign in securely',
    authenticating: 'Authenticating...',
    salesSubtitle: 'Register sales, validate stock, and deduct inventory automatically.',
    productsCount: 'saleable',
    currentSale: 'Current Sale',
    customer: 'Customer',
    customerEmail: 'Customer Email',
    retailCustomer: 'Retail Customer',
    receiptDraft: 'Optional receipt draft',
    searchProducts: 'Search product, SKU, or category',
    selectProducts: 'Select products to begin a sale.',
    units: 'Units',
    revenue: 'Revenue',
    grossProfit: 'Gross Profit',
    margin: 'Margin',
    paymentMethod: 'Payment Method',
    amountPaid: 'Amount Paid',
    change: 'Change',
    remaining: 'Remaining',
    completeSale: 'Complete Sale',
    processingSale: 'Processing sale...',
    recentSales: 'Recent Sales',
    records: 'records',
    seller: 'Seller',
    receipt: 'Receipt',
    open: 'Open',
    print: 'Print',
    pdf: 'PDF',
    emailDraft: 'Email Draft',
    stockInventory: 'Stock & Inventory',
    receiveStock: 'Receive Stock',
    adjustStock: 'Adjust Stock',
    receive: 'Receive',
    product: 'Product',
    category: 'Category',
    unitCost: 'Unit Cost',
    qtyOnHand: 'Qty on Hand',
    totalValue: 'Total Value',
    action: 'Action',
    noProducts: 'No products found matching the current filter.',
    executiveDashboard: 'Executive Dashboard',
    totalInventoryValue: 'Total Inventory Value',
    basedOnExactWac: 'Based on exact WAC',
    grossProfitLedger: 'Gross Profit (Ledger)',
    trackedAcrossSalesDays: 'Tracked across {count} sales days',
    avgProfitMargin: 'Avg Profit Margin',
    againstStrictCogs: 'Against strict outbound COGS',
    salesVsCogsTrend: 'Sales vs COGS Trend',
    costOfGoods: 'Cost of Goods (COGS)',
    totalRevenue: 'Total Revenue',
    inventoryValueSetup: 'Inventory Value Setup',
    operationalIntelligence: 'Operational Intelligence',
    stockOutAlerts: 'Stock-Out Alerts',
    reviewZeroBound: 'Click to review zero-bound inventory.',
    lowStockWarnings: 'Low Stock Warnings',
    viewUnderThreshold: 'Click to view items under threshold.',
    expiringSoon: 'Expiring Soon (30d)',
    trackedViaBatch: 'Tracked via batch history.',
    accessRestricted: 'Access Restricted',
    dashboardRestricted: "Your role '{role}' does not have permission to view the executive dashboard panels.",
    loadingBi: 'Loading BI Engine...',
    settingsSubtitle: 'Configure company identity, payments, stock, product options, and HR defaults.',
    settingsCompanySection: 'Company',
    settingsHrSection: 'Human Resources',
    settingsFinanceSection: 'Finance & Payments',
    settingsInventorySection: 'Inventory & Products',
    saveChanges: 'Save Changes',
    settingsSaved: 'Settings successfully saved.',
    companyProfile: 'Company Profile',
    companyProfileHint: 'Used in headers, mobile bar, exports and receipts.',
    companyName: 'Company Name',
    logoUrl: 'Logo URL (optional)',
    financialPreferences: 'Financial Preferences',
    financialPreferencesHint: 'Controls currency display across dashboards, POS and reports.',
    currencyCode: 'Currency Code',
    currencySymbol: 'Currency Symbol',
    decimalPlaces: 'Decimal Formatting Places',
    payments: 'Payments',
    paymentsHint: 'Add, remove, activate or deactivate reusable payment options.',
    salesPaymentMethods: 'Sales Payment Methods',
    hrPaymentTypes: 'HR Payment Types',
    inventoryProducts: 'Inventory & Products',
    inventoryProductsHint: 'Reusable options for warehouses and product registration.',
    warehouseTypes: 'Warehouse Types',
    productCategories: 'Product Categories',
    productTypes: 'Product Types',
    productUnits: 'Product Units',
    hrDefaults: 'Human Resources',
    hrDefaultsHint: 'Simple defaults for attendance and payroll rhythm.',
    hrStructure: 'HR Structure',
    hrStructureHint: 'Roles and departments used when creating or editing workers.',
    hrRoles: 'Worker Roles',
    hrDepartments: 'Departments',
    attendanceStatuses: 'Attendance Statuses',
    payFrequencies: 'Pay Frequencies',
    editListsHelpTitle: 'How configuration lists work',
    editListsHelpHint: 'Small and flexible for daily use.',
    editListsHelp1: 'Active options appear in sales, HR, products and warehouse forms after saving.',
    editListsHelp2: 'Inactive options stay in history, but stop appearing for new records.',
    activeOptions: '{active}/{total} active',
    optionName: 'Option name',
    addOption: 'Add option',
    remove: 'Remove',
    activate: 'Activate',
    deactivate: 'Deactivate',
    active: 'Active',
    inactive: 'Inactive',
    hrSubtitle: 'Manage workers, automatic payroll, salary receipts, payments, attendance and goals.',
    addPayment: 'Add Payment',
    addWorker: 'Add Worker',
    editWorker: 'Edit Worker',
    activeWorkers: 'Active Workers',
    monthlyPayroll: 'Monthly Payroll',
    pendingPayments: 'Pending Payments',
    openGoals: 'Open Goals',
    workers: 'Workers',
    payrollSheet: 'Payroll Sheet',
    attendance: 'Attendance',
    goalsDeadlines: 'Goals & Deadlines',
    payrollHint: 'Automatic monthly salary sheet generated from active workers.',
    totalPayroll: 'Total Payroll',
    paid: 'Paid',
    pending: 'Pending',
    worker: 'Worker',
    role: 'Role',
    department: 'Department',
    amount: 'Amount',
    status: 'Status',
    markPaid: 'Mark Paid',
    reopen: 'Reopen',
    noPayroll: 'No payroll entries for this month.',
    addGoal: 'Add Goal',
    editGoal: 'Edit Goal',
    goalsHint: 'Track workers who are managed by objectives instead of attendance.',
    goal: 'Goal',
    deadline: 'Deadline',
    progress: 'Progress',
    noGoals: 'No goals recorded yet.',
    controlMode: 'Control Mode',
    attendanceControlled: 'Controlled by attendance',
    goalsControlled: 'Controlled by goals and deadlines',
    controlModeHint: 'Workers controlled by goals do not appear in the monthly attendance checkbox grid.',
    goalModalHint: 'Define a clear target, deadline and completion status.',
    selectWorker: 'Select worker',
    description: 'Description',
    notes: 'Notes',
    cancel: 'Cancel',
  },
  pt: {
    dashboard: 'Painel',
    products: 'Produtos',
    inventory: 'Inventario',
    purchasing: 'Compras',
    suppliers: 'Fornecedores',
    customers: 'Fidelizacao',
    sellersResellers: 'Vendedores e Revendedores',
    humanResources: 'Recursos Humanos',
    production: 'Producao',
    salesPos: 'Vendas / Caixa',
    reporting: 'Relatorios',
    auditLogs: 'Auditoria',
    users: 'Administracao de Utilizadores',
    settings: 'Definicoes',
    inventorySystem: 'Sistema de Inventario',
    logout: 'Sair',
    welcomeBack: 'Bem-vindo de volta',
    signInSubtitle: 'Entre para gerir as operacoes diarias.',
    emailAddress: 'Email',
    loginIdentifier: 'Email, username ou telefone',
    password: 'Senha',
    signInSecurely: 'Entrar com seguranca',
    authenticating: 'A autenticar...',
    salesSubtitle: 'Registe vendas, valide stock e desconte inventario automaticamente.',
    productsCount: 'a venda',
    currentSale: 'Venda Atual',
    customer: 'Cliente',
    customerEmail: 'Email do Cliente',
    retailCustomer: 'Cliente de Balcao',
    receiptDraft: 'Opcional para rascunho de recibo',
    searchProducts: 'Pesquisar produto, SKU ou categoria',
    selectProducts: 'Selecione produtos para iniciar a venda.',
    units: 'Unidades',
    revenue: 'Receita',
    grossProfit: 'Lucro Bruto',
    margin: 'Margem',
    paymentMethod: 'Metodo de Pagamento',
    amountPaid: 'Valor Pago',
    change: 'Troco',
    remaining: 'Em Falta',
    completeSale: 'Finalizar Venda',
    processingSale: 'A processar venda...',
    recentSales: 'Vendas Recentes',
    records: 'registos',
    seller: 'Vendedor',
    receipt: 'Recibo',
    open: 'Abrir',
    print: 'Imprimir',
    pdf: 'PDF',
    emailDraft: 'Rascunho Email',
    stockInventory: 'Stock e Inventario',
    receiveStock: 'Receber Stock',
    adjustStock: 'Ajustar Stock',
    receive: 'Receber',
    product: 'Produto',
    category: 'Categoria',
    unitCost: 'Custo Unitario',
    qtyOnHand: 'Qtd. em Stock',
    totalValue: 'Valor Total',
    action: 'Acao',
    noProducts: 'Nenhum produto encontrado para este filtro.',
    executiveDashboard: 'Painel Executivo',
    totalInventoryValue: 'Valor Total do Inventario',
    basedOnExactWac: 'Baseado no custo medio exato',
    grossProfitLedger: 'Lucro Bruto (Registo)',
    trackedAcrossSalesDays: 'Registado em {count} dias de venda',
    avgProfitMargin: 'Margem Media',
    againstStrictCogs: 'Contra custo de saida rigoroso',
    salesVsCogsTrend: 'Tendencia Vendas vs Custos',
    costOfGoods: 'Custo dos Produtos Vendidos',
    totalRevenue: 'Receita Total',
    inventoryValueSetup: 'Composicao do Valor do Inventario',
    operationalIntelligence: 'Inteligencia Operacional',
    stockOutAlerts: 'Alertas de Stock Esgotado',
    reviewZeroBound: 'Clique para rever stock zerado.',
    lowStockWarnings: 'Avisos de Stock Baixo',
    viewUnderThreshold: 'Clique para ver itens abaixo do minimo.',
    expiringSoon: 'A Expirar em Breve (30d)',
    trackedViaBatch: 'Controlado pelo historico de lotes.',
    accessRestricted: 'Acesso Restrito',
    dashboardRestricted: "O perfil '{role}' nao tem permissao para ver o painel executivo.",
    loadingBi: 'A carregar motor BI...',
    settingsSubtitle: 'Configure identidade da empresa, pagamentos, stock, produtos e padroes de RH.',
    settingsCompanySection: 'Empresa',
    settingsHrSection: 'Recursos Humanos',
    settingsFinanceSection: 'Financeiro e Pagamentos',
    settingsInventorySection: 'Inventario e Produtos',
    saveChanges: 'Guardar Alteracoes',
    settingsSaved: 'Definicoes guardadas com sucesso.',
    companyProfile: 'Perfil da Empresa',
    companyProfileHint: 'Usado em cabecalhos, barra movel, exportacoes e recibos.',
    companyName: 'Nome da Empresa',
    logoUrl: 'URL do Logo (opcional)',
    financialPreferences: 'Preferencias Financeiras',
    financialPreferencesHint: 'Controla moeda nos paineis, caixa e relatorios.',
    currencyCode: 'Codigo da Moeda',
    currencySymbol: 'Simbolo da Moeda',
    decimalPlaces: 'Casas Decimais',
    payments: 'Pagamentos',
    paymentsHint: 'Adicione, remova, active ou desactive opcoes reutilizaveis de pagamento.',
    salesPaymentMethods: 'Metodos de Pagamento das Vendas',
    hrPaymentTypes: 'Tipos de Pagamento de RH',
    inventoryProducts: 'Inventario e Produtos',
    inventoryProductsHint: 'Opcoes reutilizaveis para armazens e produtos.',
    warehouseTypes: 'Tipos de Armazem',
    productCategories: 'Categorias de Produto',
    productTypes: 'Tipos de Produto',
    productUnits: 'Unidades de Produto',
    hrDefaults: 'Recursos Humanos',
    hrDefaultsHint: 'Padroes simples para assiduidade e pagamentos.',
    hrStructure: 'Estrutura de RH',
    hrStructureHint: 'Cargos e departamentos usados ao criar ou editar trabalhadores.',
    hrRoles: 'Cargos dos Trabalhadores',
    hrDepartments: 'Departamentos',
    attendanceStatuses: 'Estados de Assiduidade',
    payFrequencies: 'Frequencias de Pagamento',
    editListsHelpTitle: 'Como funcionam as listas',
    editListsHelpHint: 'Simples e flexivel para uso diario.',
    editListsHelp1: 'As opcoes activas aparecem nas vendas, RH, produtos e armazens depois de guardar.',
    editListsHelp2: 'As opcoes inactivas ficam no historico, mas deixam de aparecer em novos registos.',
    activeOptions: '{active}/{total} activas',
    optionName: 'Nome da opcao',
    addOption: 'Adicionar opcao',
    remove: 'Remover',
    activate: 'Activar',
    deactivate: 'Desactivar',
    active: 'Activo',
    inactive: 'Inactivo',
    hrSubtitle: 'Gerir trabalhadores, folha salarial automatica, recibos de salario, pagamentos, assiduidade e metas.',
    addPayment: 'Adicionar Pagamento',
    addWorker: 'Adicionar Trabalhador',
    editWorker: 'Editar Trabalhador',
    activeWorkers: 'Trabalhadores Activos',
    monthlyPayroll: 'Folha Salarial Mensal',
    pendingPayments: 'Pagamentos Pendentes',
    openGoals: 'Metas em Aberto',
    workers: 'Trabalhadores',
    payrollSheet: 'Folha Salarial',
    attendance: 'Assiduidade',
    goalsDeadlines: 'Metas e Deadlines',
    payrollHint: 'Folha salarial mensal gerada automaticamente a partir dos trabalhadores activos.',
    totalPayroll: 'Total da Folha',
    paid: 'Pago',
    pending: 'Pendente',
    worker: 'Trabalhador',
    role: 'Funcao',
    department: 'Departamento',
    amount: 'Valor',
    status: 'Estado',
    markPaid: 'Marcar Pago',
    reopen: 'Reabrir',
    noPayroll: 'Sem salarios para este mes.',
    addGoal: 'Adicionar Meta',
    editGoal: 'Editar Meta',
    goalsHint: 'Acompanhe trabalhadores geridos por objectivos em vez de assiduidade.',
    goal: 'Meta',
    deadline: 'Deadline',
    progress: 'Progresso',
    noGoals: 'Ainda nao existem metas registadas.',
    controlMode: 'Modo de Controlo',
    attendanceControlled: 'Controlado por assiduidade',
    goalsControlled: 'Controlado por metas e deadlines',
    controlModeHint: 'Trabalhadores controlados por metas nao aparecem na grelha mensal de assiduidade.',
    goalModalHint: 'Defina uma meta clara, deadline e estado de conclusao.',
    selectWorker: 'Selecionar trabalhador',
    description: 'Descricao',
    notes: 'Notas',
    cancel: 'Cancelar',
  },
};

const interpolate = (text, params = {}) =>
  Object.entries(params).reduce((acc, [key, value]) => acc.replaceAll(`{${key}}`, String(value)), text);

export const LanguageContext = createContext();

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState(() => localStorage.getItem('soul_language') || 'en');

  useEffect(() => {
    localStorage.setItem('soul_language', language);
  }, [language]);

  const value = useMemo(() => {
    const dictionary = translations[language] || translations.en;
    return {
      language,
      setLanguage,
      t: dictionary,
      translate: (key, params) => interpolate(dictionary[key] || translations.en[key] || key, params),
    };
  }, [language]);

  return (
    <LanguageContext.Provider value={value}>
      {children}
    </LanguageContext.Provider>
  );
};
